server:
  port: 9013

spring:
  application:
    name: gateway-limiter
  cloud:
    gateway:
      routes:
      - id: limit_route_id  #id标签配置的是router的id，每个router都需要一个唯一的id
        uri: http://httpbin.org:80  #uri配置的是将请求路由到哪里
        predicates:
        # 1、跟时间相关的predicates,这个After就是指定了它的Gateway web handler类为AfterRoutePredicateFactory,BeforeRoutePredicateFactory、BetweenRoutePredicateFactory
        - After=2002-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
            redis-rate-limiter.burstCapacity: 3 #令牌桶总容量
  redis:
    host: 10.37.31.88
    port: 8081
    database: 0
    password: 8QXTtgBf
