server:
  port: 9011
#指定了程序的spring的启动文件为after_route文件
spring:
  profiles:
    active: after_route

#一个新文件
#  在application.yml再建一个配置文件，语法是三个横线，在此配置文件中通过spring.profiles来配置文件名，和spring.profiles.active一致
---
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
      - id: after_route_id  #id标签配置的是router的id，每个router都需要一个唯一的id
        uri: http://httpbin.org:80  #uri配置的是将请求路由到哪里
        predicates:
# 1、跟时间相关的predicates,这个After就是指定了它的Gateway web handler类为AfterRoutePredicateFactory,BeforeRoutePredicateFactory、BetweenRoutePredicateFactory
#        - After=2022-01-20T17:42:47.789-07:00[America/Denver]
#        - Before=2019-03-27T10:49:30.909+08:00[Asia/Shanghai]
#        - Between=2019-03-27T10:51:30.909+08:00[Asia/Shanghai], 2019-03-27T11:49:30.909+08:00[Asia/Shanghai]
# 2、Cookie Route Predicate Factory，跟cookie相关的断言
# 请求带有cookie名为name, cookie值为forezp 的请求将都会转发到uri为 http://httpbin.org:80/get的地址上。
#        - Cookie=name, forezp
# 3、Header Route Predicate Factory，当此断言匹配了请求的header名和值时，断言通过，进入到router的规则中去
#        当请求的Header中有X-Request-Id的header名，且header值为数字时
#        - Header=X-Request-Id, \d+
#4、Host Route Predicate Factory，需要一个参数即hostname，它可以使用. * 等去匹配host，这个参数会匹配请求头中的host的值，一致，则请求正确转发
#失败失败失败失败失败失败失败失败失败失败
        - Host=**127.0.0.1**
#5、Method Route Predicate Factory 请求方法断言，需要一个参数，即请求的类型。比如GET类型的请求都转发到此路由
#        - Method=POST
#6、Path Route Predicate Factory 路径匹配断言，需要一个参数: 一个spel表达式，应用匹配路径。
#  将获得如下路径：http://httpbin.org:80/forms/post，Path将拼接到Uri后边
#        - Path=/forms/{segment}
#7、Query Route Predicate Factory 请求参数匹配，需要2个参数:一个参数名和一个参数值的正则表达式。
#  配置了请求中含有参数foo，并且foo的值匹配ba.，则请求命中路由
#        - Query=foo, ba.
#        也可以只填一个参数，填一个参数时则只匹配参数名
#        - Query=foo
#8、RemoteAddr Route Predicate Factory 远程IP地址匹配，如果请求的远程地址是，例如192.168.1.10，则此路由将匹配。
#失败失败失败失败失败失败失败失败
#        - RemoteAddr=172.29.2.195/24


