server:
  port: 8090
spring:
  application:
    name: eurekaServer01

eureka:
  instance:
    hostname: eurekaServerHost01
  client:
    register-with-eureka: false # 是否注册自己到eureka
    fetch-registry: false # 是否拉取其他eureka上的数据(如：注册列表) false表明自己是eureka server
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      服务的注册信息二次传播顺序
      defaultZone: http://eurekaServerHost02:8091/eureka/
  server:
    enable-self-preservation: false  #当server在15分钟内(900s)，比值低于percent，即少了15%的微服务心跳，server会进入自我保护状态，Self-Preservation。